/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal app workflows. It is checked in
// here so the workspace example typechecks before the dev server is run.
